version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    container_name: fastapi-app-test
    restart: on-failure
    env_file:
      - .env
    networks:
      custom-network-test:

networks:
  custom-network-test:
    driver: bridge
