version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: fastapi-app-dev
    restart: on-failure
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    networks:
      custom-network-dev:

networks:
  custom-network-dev:
    driver: bridge
